### ISSUE TITLE
Github Push Permissions

### ISSUE THREAD

**Issue by mpahrens** [MattWorzala/BoardGames#1]
I do not have push permissions for some reason, so could you check to see if the settings are correct?

**Comment by MattWorzala** [comment]
You haven't accepted the invite to it. It should be in your email but if not [here](https://github.com/MattWorzala/BoardGames/invitations) it is.

**Comment by mpahrens** [comment]
Thanks! I thought I had, but it must have messed up on my end. All good now :)
